// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvslqkksxuacloxkcutt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2c2xxa2tzeHVhY2xveGtjdXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjIwNjcsImV4cCI6MjA2ODU5ODA2N30.Vhx5_5kb0dqzgX7U4t_uQpwO19SKk9XSqWf2WDS2HEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});